### ISSUE TITLE
ffmpeg-hud.py fails to start, invalid syntax.

### ISSUE THREAD

**Issue by bmorrison4** [letsRobot/letsrobot#38]
using `ffmpeg-hud.py` spits out the following traceback

```Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
    File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
    File "/home/pi/letsrobot/video/ffmpeg-hud.py", line 90, in startVideoCapture
        HUD = drawBaseHud()
    File "/home/pi/letsrobot/video/ffmpeg-hud.py", line 163, in drawBaseHUD
        image = Image.new("RGBA", (x_rex, y_res), color = (0,0,0,0))
    File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2063, in new
        return Image().__new(core.fill(mode, size, color))
TypeError: an integer is required```

**Comment by Nocturnal42** [comment]
That’s new. I’m assuming this is on a Pi. Is it a fresh install or an old image? Is this a newly created robot or an old one?

**Comment by bmorrison4** [comment]
LED bot with a fresh image. Pre-reqs are installed.

**Comment by Nocturnal42** [comment]
Have you set a resolution for LED bot through the site, or just left the default?

**Comment by bmorrison4** [comment]
It's set on the site.

**Comment by Nocturnal42** [comment]
That rules out pretty much everything obvious. I’ll see if I can fish out a webcam and setup a test bed to take a look.

**Comment by bmorrison4** [comment]
I can also set up LED bot on RSSH if you need it.
